DELETE FROM word;
--1
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('łagodzić', 'alleviate', 'She needed something to alleviate the pain in her back.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('astrologia', 'astrology', 'Max, who studies astrology, believes that the stars can predict the future.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('rozróżniać', 'differentiate', 'It was hard to differentiate between the identical twins.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zakłócać', 'disrupt', 'The loud crash disrupted the class lecture.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('równanie', 'equation', 'I used the Pythagorean theorem to solve the equation.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pomylić się', 'err', 'The pilot erred in his estimate of the time it would take to make the trip.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('błędny', 'erroneous', 'The child held the erroneous belief that time machines were real.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('gorączkowy', 'frantic', 'The cat became frantic when I tried to give it a bath.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kadłub', 'hull', 'After the wreck at sea, the ship’s hull was the last part to sink.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nieumyślnie', 'inadvertent', 'She made an inadvertent error when she knocked over the nail polish.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('improwizować', 'improvise', 'There was no meat for the pizza, so we improvised with what was in the fridge.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('szerokość geograficzna', 'latitude', 'The device was able to tell the traveler his exact latitude.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('marynarz', 'mariner', 'The old mariner used his telescope to find the shore.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('mnogość', 'multitude', 'A multitude of people were waiting at the airport.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('uciążliwość', 'nuisance', 'The teenager considered her noisy little brothers to be quite a nuisance.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('trwałość', 'permanence', 'Poor results will threaten the permanence of the new teaching system.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('obracać się', 'revolve', 'My life revolves around sports.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('uspokoić', 'soothe', 'The mother soothed her crying baby by rocking him in her arms.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('utknięty', 'stranded', 'When the plane left, my sister and I were stranded in China.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niestabilny', 'volatile', 'The volatile volcano might explode at any moment.', 'ADJECTIVE', 'HARD');
--2
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('żmudny', 'arduous', 'The explorers began their arduous hike up the steep mountain.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('osiągnąć', 'attain', 'In two more years, I will attain my high school diploma.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('współistnieć', 'coexist', 'Our pets coexist at our home with little or no problems.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pojąć', 'conceive', 'The child could not conceive the actual size of the Earth.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wątpliwy', 'dubious', 'The police thought that the man’s description of the crime was dubious.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ego', 'ego', 'Kelly’s ego made her think that she was some kind of a superhero.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('elastyczny', 'elastic', 'He attached the elastic bungee to his legs before he jumped off the platform.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przedsięwzięcie', 'endeavor', 'The company’s new advertising endeavor ended in a horrible failure.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wygrawerować', 'engrave', 'The couple engraved their names onto the old pine tree.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wykopać', 'excavate', 'The team wishes to excavate the site in hopes of finding fossils.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('poszarpane', 'jagged', 'The swimmer was hurt when he fell on the jagged rocks.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('miejsce', 'locale', 'The spa was the perfect locale for my mother to relax and enjoy her vacation.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('forma', 'mold', 'Using a cupcake mold will ensure that they come out just right.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('jawne', 'outright', 'Everyone knew that the boy’s story was an outright lie.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('krawędź', 'periphery', 'A beautiful floral pattern is on the periphery of the stationery.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('tynk', 'plaster', 'He used plaster to fill in the cracks in the old walls.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('łopata', 'shovel', 'The boy grabbed his shovel and got all of the snow off of the sidewalk.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kostny', 'skeletal', 'We studied the skeletal system in anatomy class.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ziemski', 'terrestrial', 'There are billions of terrestrial life forms.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('okrutny', 'vicious', 'The vicious dog tried to bite the small child.', 'ADJECTIVE', 'HARD');
--3
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('absurdalny', 'absurd', 'That group of people making animal noises sounds completely absurd.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('anemia', 'anemia', 'When she first developed anemia, she became tired often.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('arystokracja', 'aristocracy', 'Most members of the aristocracy were very well-fed.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('arystokrata', 'aristocrat', 'The aristocrat did not need a job because his family was wealthy.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('strój (na specjalną okazję)', 'attire', 'Everyone wore their best attire to the president’s daughter’s wedding.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('szał', 'craze', 'Wearing bright red socks was a craze when I was in high school.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('powiększać', 'enlarge', 'The classrooms were enlarged over the summer to make room for more students.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nadmiar', 'excess', 'Because it never got cold that winter, many stores had an excess of coats.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kobiecy', 'feminine', 'Many of the older people thought his long hair made him look too feminine.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('znak rozpoznawczy', 'hallmark', 'Different types o f pasta and tomato sauces are hallmarks of Italian food.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('podkładka', 'pad', 'Football players wear shoulder pads to keep them safe.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('dominujący', 'predominant', 'Before cars were invented, horses were the predominant method of travel.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('renomowany', 'reputable', 'The service from the less than reputable company made her angry.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('róż (kosmetyk)', 'rouge', 'Even when she didn’t wear rouge, her cheeks appeared red.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('oznaczać', 'signify', 'A red octagon is used to signify to stop.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pasek', 'strap', 'She put the strap of her purse over her shoulder and walked out of the door.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('plątanina', 'tangle', 'The laces of his shoes were in such a tangle that he could not untie them.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('próżność', 'vanity', 'Her vanity won’t allow her to pass a mirror without looking at herself.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('rywalizować', 'vie', 'The three boys vied for the prize in the chemistry contest.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wulgarny', 'vulgar', 'Her vulgar behavior got her into trouble with her parents.', 'ADJECTIVE', 'HARD');
--4
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('poddasze', 'attic', 'There were two windows in their attic.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kawałek', 'chunk', 'When they broke open the rock, they saw it was filled with chunks of gold.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('miejski', 'civic', 'Most of the important civic buildings are located downtown.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zejście', 'descent', 'During the space shuttle’s descent, the Earth became larger and larger.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('gwar', 'din', 'The din of the rusty machinery made the factory a horrible place to work.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niezadowolenie', 'dissatisfy', 'He was dissatisfied with his meal.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zamieszanie', 'fuss', 'The child made an awful fuss because she didn’t want to go to bed.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wykwintny', 'gourmet', 'In order to get a gourmet meal, you have to eat at an expensive restaurant.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('stąd', 'hence', 'There is a strike, hence the delay.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wewnętrzny', 'intrinsic', 'Paper money has no intrinsic value. It is useful simply because society says it is.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('czajnik', 'kettle', 'The soup was being cooked in a large kettle.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ministerstwo', 'ministry', 'The Ministry of Trade is responsible for taxing imports and exports.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('męka', 'ordeal', 'Driving in the snowstorm was an ordeal she’d never forget.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('szczery', 'outspoken', 'She was an outspoken critic about the new banking laws.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przepracowanie', 'overwork', 'After working for three weeks with only one day of rest, Judy was overworked.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('konkretny', 'particular', 'The dress shop didn’t have the particular dress she was looking for.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ostry (zapach)', 'pungent', 'The garlic made the soup taste so pungent that the chef wouldn’t serve it.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('chrapać', 'snore', 'It was impossible to get to sleep because my husband snored.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('solidnie', 'soundly', 'The nearest opponent was ten meters behind. She won the race soundly.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kierownik', 'superintendent', 'The superintendent decided to close the schools because of the weather.', 'NOUN', 'HARD');
--5
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zmieniać kolejno', 'alternate', 'The best exercise alternates muscle and heart strengthening.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('skruszony', 'apologetic', 'The boy felt apologetic after losing his sister’s favorite toy.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('łagodny', 'benign', 'Many spiders look scary, but most are actually benign.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zwęglić', 'char', 'While Frank went inside to get the mustard, he accidentally charred the hotdogs.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wyjaśnić', 'clarify', 'Drew tried to clarify all the functions of Michelle’s new computer.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zaniepokojenie', 'distress', 'Failing a class caused the student a lot of distress.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('uparty', 'dogged', 'Her dad bought her a new jacket after her dogged requests for one.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nastąpić', 'ensue', 'After a few minutes of lightening, thunder ensued.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('brać gwałtowny wdech', 'gasp', 'John always gasps when watching a scary movie.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('negocjować', 'negotiate', 'Mario and Joe took a long time negotiating the contract between the companies.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nadmierna dawka', 'overdose', 'Jacob’s skin was burned from an overdose of sunshine.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('perswazja', 'persuasion', 'The persuasion of his argument convinced the customer to buy the laptop.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('sztafeta', 'relay', 'James was the fastest on his team, so he ran the last part of the relay', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niechęć', 'reluctance', 'Marie took out the trash with great reluctance.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przedstawić ponownie', 'restate', 'Mrs. Davies restated the test question to the class.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('sezam', 'sesame', 'I used the buns with the sesame seeds on them.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('sączyć', 'sip', 'Emily relaxed on the beach, sipping apple juice through a straw.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('próg', 'verge', 'Harry was on the verge of leaving her house when the phone rang.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('oględny', 'wary', 'Lily was wary of going to school because she hadn’t done her homework.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wahać się', 'waver', 'I wavered between eating the apple or the cake for a snack.', 'VERB', 'HARD');
--6
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('na brzeg', 'ashore', 'The sailors rowed the boat ashore after a long voyage at sea.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zaprzeczać', 'contradict', 'Jake was always fighting with his little sister because she kept contradicting him.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odpowiednik', 'counterpart', 'His foreign counterpart signed the agreement on behalf of their government.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pozbawiony', 'devoid', 'The room was devoid of any furniture or decoration.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('rozejść się', 'diverge', 'The two paths diverged in the woods, and she had to choose which one to take.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('omijać', 'elude', 'Despite his efforts, the solution to the problem continued to elude him.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zarodek', 'embryo', 'The embryo was developing normally in the early stages of pregnancy.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odeprzeć', 'fend', 'She had to work extra hard to fend off the competitor and win the race.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zmyślony', 'fictitious', 'The author used a fictitious name to publish her controversial novel.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('gazeta', 'gazette', 'The government published a notice in the official gazette to announce the new law.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('jednolity', 'homogeneous', 'All of the houses in that district were boring and homogenous.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('tamować', 'obstruct', 'The fallen tree obstructed the road, causing a traffic jam.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zanurzyć się', 'plunge', 'She took a plunge into the icy water, gasping at the shock of the cold.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przedłużać', 'prolong', 'Prolonging the project would require additional resources and manpower.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nagłaśniać', 'publicize', 'The company decided to publicize their new product through a nationwide advertising campaign.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nieliczny', 'sparse', 'The vegetation was sparse in the desert, with only a few hardy species able to survive.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nadwyżka', 'surplus', 'The country had a surplus of grain, leading to lower prices for farmers.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('teoretyzować', 'theorize', 'The scientist theorized that the phenomenon was caused by a previously undiscovered particle.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('sprawdzić', 'verify', 'The results of the experiment needed to be verified before they could be accepted as fact.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('energiczny', 'vigorous', 'The athlete trained with vigorous determination, pushing himself to the limit every day.', 'ADJECTIVE', 'HARD');
--7
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ołtarz', 'altar', 'She knelt at the altar and offered a prayer.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zapalenie stawów', 'arthritis', 'His arthritis made it difficult for him to move his joints.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('botanika', 'botany', 'The botany professor was knowledgeable about all aspects of plant life.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wiarygodny', 'credible', 'The eyewitness testimony was considered credible in the court of law.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zmarły', 'deceased', 'The deceased was remembered fondly by his friends and family.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('oszustwo', 'deception', 'The deception was discovered and the culprit was punished.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('rozszyfrować', 'decipher', 'The cryptographer worked tirelessly to decipher the coded message.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('gnój', 'dung', 'The farmer used the dung to fertilize his crops.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zmierzch', 'dusk', 'As dusk fell, the campers settled around the fire.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('spełnić', 'gratify', 'The compliment from his boss gratified him, confirming his hard work was recognized.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('doskonalić', 'hone', 'The swordsman honed his skills every day, seeking to be the best in the land.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('utłuc', 'mash', 'She mashed the potatoes with a fork to make them smooth.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ozdobny', 'ornate', 'The ornate jewelry was passed down from generation to generation in the royal family.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zapalenie płuc', 'pneumonia', 'He was diagnosed with pneumonia and had to be hospitalized.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('parapsychologiczny', 'psychic', 'The psychic was able to sense the presence of spirits.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('chory psychicznie', 'psychotic', 'The psychotic patient was a danger to himself and others, requiring constant supervision.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zakres', 'scope', 'The scope of the project was vast, requiring the efforts of many experts.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('złowieszczy', 'sinister', 'The sinister atmosphere made the hair on the back of her neck stand up.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('swary', 'strife', 'The constant strife between the two factions was damaging to the community.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('terapeutyczny', 'therapeutic', 'The therapeutic massage helped to relieve her stress and tension.', 'ADJECTIVE', 'HARD');
--8
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zatłoczony', 'congested', 'The traffic was congested and it took a long time to reach the destination.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kurier', 'courier', 'He worked as a courier delivering packages to different locations.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zdeformowany', 'deform', 'The accident caused the metal to deform and become misshapen.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('etykieta', 'etiquette', 'Good manners and etiquette are important in social situations.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ekskluzywny', 'exclusive', 'The exclusive club only admitted members with a certain level of wealth and status.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('fracht', 'freight', 'The shipment of goods was sent by freight to the port.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('garment', 'garment', 'She carefully selected a garment from the store to wear to the event.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('bezsenność', 'insomnia', 'He suffered from insomnia and found it difficult to fall asleep.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('intuicyjny', 'intuitive', 'She had an intuitive sense of what people needed and always tried to help.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odpowiedzialny', 'liable', 'The company was liable for the damages caused by their faulty product.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('obsesyjny', 'obsess', 'He became obsessed with collecting stamps and spent all his time and money on it.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ponad miarę', 'overboard', 'He went overboard with his spending and soon found himself in debt.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('premia', 'premium', 'The premium package included additional features and benefits for the customer.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przywilej', 'privilege', 'It was a privilege to be invited to the exclusive event and meet important people.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('napędzać', 'propel', 'The new technology allowed the spacecraft to propel faster through the galaxy than ever before.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('społeczizować', 'socialize', 'She enjoyed socializing with her friends at the party.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('tłumić', 'suppress', 'The government tried to suppress dissent and maintain control.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('tramwaj', 'tram', 'The tram was a convenient and efficient way to travel around the city.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niepokoić', 'unsettle', 'The sudden change in plans unsettled her and she felt uncertain about what to do next.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zniekształcony', 'warp', 'The extreme heat caused the metal to warp and become distorted.', 'VERB', 'HARD');
--9
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('tętnica', 'artery', 'The blocked artery caused a heart attack.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pogorszenie', 'deterioration', 'The deterioration of the building was evident as the walls started to crumble.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('uciekający', 'elusive', 'The answer to the puzzle was elusive and it took a long time to figure it out.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zbieranie pożywienia', 'forage', 'The animals foraged for food in the forest.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przeszkadzać', 'impede', 'The heavy traffic impeded their progress on the road.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('prowokować', 'induce', 'The strong smell induced a headache in him.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nieodłączne', 'inseparable', 'They were inseparable friends since childhood.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nie ważny', 'invalid', 'The document was declared invalid due to missing signatures.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('powiększać', 'magnify', 'The microscope allowed them to magnify the tiny specimen.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('główny nurt', 'mainstream', 'The new idea was not yet part of the mainstream thinking.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('mikroba', 'microbe', 'The microbe caused a serious infection in the patient.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niedostrzegalny', 'negligible', 'The difference in size was negligible and barely noticeable.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('paraliż', 'paralysis', 'The spider s bite caused paralysis in the victim.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('szkodnik', 'pest', 'The farmers tried different methods to get rid of the pest that was damaging their crops.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zapanować', 'prevail', 'Despite the challenges, his determination and hard work eventually prevailed.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('oddychanie', 'respiration', 'The process of respiration was studied in detail in the biology class.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pęknięcie', 'rupture', 'The pressure inside the tank caused a rupture and a leak.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('dziki', 'savage', 'The savage attack left the victim badly injured.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('osłabienie', 'stun', 'The loud explosion stunned everyone in the room.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('podatne', 'susceptible', 'She was susceptible to colds and caught one every winter.', 'ADJECTIVE', 'HARD');
--10
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('akumulować', 'accumulate', 'The company accumulated a large amount of wealth over the years.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('powietrzny', 'aerial', 'The aerial view of the city was breathtaking.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('urządzenie', 'apparatus', 'The apparatus was used to perform experiments in the laboratory.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('lawina', 'avalanche', 'The avalanche was triggered by the sound of the explosion.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('spójność', 'consistency', 'The consistency of the mixture was just right for making cakes.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('konwekcja', 'convection', 'The convection oven cooked the food evenly and quickly.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('rozładować', 'discharge', 'The battery was discharged after being left on for too long.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nieuszkodzony', 'intact', 'The statue was found intact despite being buried for centuries.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('śmiertelny', 'mortal', 'The hero had to face his mortal enemies in the final battle.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zwiastun', 'omen', 'The appearance of the comet was seen as a bad omen by some people.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zachmurzony', 'overcast', 'The sky was overcast, making it difficult to see the sun.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wzruszający', 'poignant', 'The movie was so poignant that it left everyone in the theater in tears.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('strażnik', 'ranger', 'The ranger was responsible for maintaining order in the park.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('gruz', 'rubble', 'The rubble of the collapsed building was cleared away.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odosobnić', 'seclude', 'The writer decided to seclude himself in the countryside to work on his new book.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('na bok', 'sideways', 'The car spun sideways and hit the tree.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('płakać', 'sob', 'The child was sobbing uncontrollably after losing her teddy bear.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('trzeźwy', 'sober', 'After a night of heavy drinking, he was unable to walk in a sober manner.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('plamka', 'speck', 'The speck of dirt on the lens made it difficult to take a clear photo.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wychowanie', 'upbringing', 'Her strict upbringing made her very disciplined and organized.', 'NOUN', 'HARD');
--11
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('adwokat', 'advocate', 'She is an advocate for her rights.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('upoważnienie', 'authorize', 'The manager authorized the purchase of new equipment.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('cywil', 'civilian', 'The civilian population was evacuated from the war zone.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('towar', 'commodity', 'Oil is a valuable commodity.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('podbój', 'conquest', 'The conquest of the territory was a major achievement for the army.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ujawnić', 'disclose', 'The company was forced to disclose its financial information.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('dynamika', 'dynamics', 'The dynamics of the team have changed since the new manager arrived.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zapisać się', 'enroll', 'She enrolled in a cooking class to learn new skills.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zazdrosny', 'envious', 'She was envious of her success.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('euforia', 'euphoria', 'The team was in a state of euphoria after winning the championship.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('świąteczny', 'festive', 'The city was decorated with lights for the festive season.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wesoły', 'jolly', 'He was in a jolly mood after winning the lottery.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('soczewica', 'lentil', 'Lentil soup is a popular dish in many countries.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('marszałek', 'marshal', 'The marshal led the parade down Main Street.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('morale', 'morale', 'Their morale was low after losing several games in a row.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przepowiednia', 'prophecy', 'The prophecy warned of a great disaster.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('mądry', 'sage', 'He was a sage, known for his wisdom and knowledge.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('senat', 'senate', 'The senator spoke on behalf of the Senate.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nastrój', 'sentiment', 'The sentiment among the citizens was positive after the election results.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niepokój', 'unrest', 'The unrest in the country continued for several days.', 'NOUN', 'HARD');
--12
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ozdabiać', 'adorn', 'She adorned her hair with fresh flowers.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('szczęście', 'bliss', 'They were in a state of bliss on their honeymoon.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('służący', 'butler', 'The butler brought the guests their drinks.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('skurcze', 'cramp', 'She woke up in the middle of the night with a cramp in her leg.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zrujnowany', 'dilapidated', 'The building was in a dilapidated state and in need of repair.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wywoływać', 'evoke', 'The music evokes memories of childhood.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pożegnanie', 'farewell', 'They said farewell to their friends at the airport.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kran', 'faucet', 'She turned off the faucet after washing the dishes.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('brud', 'filth', 'The room was in a state of filth and disarray.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wada', 'flaw', 'The diamond was perfect, with no flaws.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('uśmiech', 'grin', 'He could not help but grin when he heard the good news.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('sprzątanie', 'housekeeping', 'The hotels housekeeping staff does an excellent job of keeping the rooms clean.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kopiec', 'mound', 'The archeologists found ancient artifacts on a large mound of dirt.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('osłabiony', 'numb', 'His hand was numb from holding the cold glass for too long.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('beztroski', 'reckless', 'He was reckless and took unnecessary risks.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('tablica', 'slate', 'The teacher wiped the slate clean and started a new lesson.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('krzesło', 'stool', 'She sat on a stool while she painted the walls.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('testament', 'testament', 'He left a testament to his family and friends.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('drewno', 'timber', 'The logs were cut into small pieces of timber for building.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zawór', 'valve', 'The engineer checked the valve for leaks.', 'NOUN', 'HARD');
--13
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('potwierdzać', 'certify', 'The doctor certified that the patient was healthy enough to travel.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('współpracować', 'collaborate', 'The two companies collaborated on the new project.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('składać', 'compile', 'The librarian compiled a list of all the books in the library.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('kontradować', 'counteract', 'The medicine was designed to counteract the effects of the poison.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('hamować', 'curb', 'The city installed speed bumps to curb speeding driving in residential areas.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('diagnozować', 'diagnose', 'The doctor diagnosed the patient with a rare illness.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('uchwalać', 'enact', 'The government enacted a new law to protect the environment.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('federacja', 'federation', 'The European Union is a federation of European countries.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('brutto', 'gross', 'The company*s gross revenue was over a million dollars last year.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ludzki', 'humane', 'The organization works to promote humane treatment of animals.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niedopuszczalny', 'intolerable', 'The conditions in the prison were intolerable and inhumane.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('potrzebujący', 'needy', 'The charity provides food and shelter for the needy.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('uczciwy', 'honest', 'She was an honest person and always told the truth.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('obietnica', 'pledge', 'The president made a pledge to reduce poverty and increase education.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zakazywać', 'prohibit', 'The government prohibits the sale of certain drugs.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pośpieszny', 'rash', 'He made a rash decision without thinking it through.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('renderować', 'render', 'The artist used computer software to render a 3D model of the building.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('owdowienie', 'smallpox', 'The smallpox vaccine has been effective in eradicating the disease.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przekazywać', 'transmit', 'The transmission tower transmitted the radio signal to the surrounding area.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ślub', 'vow', 'They made a vow to love and cherish each other for the rest of their lives.', 'NOUN', 'HARD');
--14
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('maskować', 'camouflage', 'The military used camouflage to blend in with the environment.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('rozmyślać', 'contemplate', 'She sat quietly, contemplating the meaning of life.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ustalać', 'contend', 'The two companies contended for the contract, but only one could win.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('łóżko', 'cot', 'The soldiers set up their cots in the tent for the night.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zaciągać się', 'enlist', 'He enlisted in the army after finishing high school.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('granica', 'frontier', 'The western frontier was a dangerous and unknown place in the 19th century.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('podręcznik', 'handbook', 'The new employee was given a handbook with all the company*s policies.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niepewny', 'hesitant', 'He was hesitant to speak in front of such a large crowd.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('bujny', 'lush', 'The lush forest was filled with all kinds of animals and plants.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('szpik', 'marrow', 'The bone marrow transplant was successful, and the patient was able to recover.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ubranie', 'outfit', 'She put on her favorite outfit to go to the party.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('łapa', 'paw', 'The cat lifted its paw to catch the toy.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('drżenie', 'quiver', 'She could feel a quiver in her voice as she spoke.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wspaniały', 'splendid', 'The castle was a splendid sight to behold.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zaginiony', 'stray', 'The stray dog wandered the streets looking for food.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('znaczący', 'substantial', 'The company*s substantial profits allowed for investment in new technology.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pochodnia', 'torch', 'The Olympic torch is passed from runner to runner to symbolize peace and unity.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('obszar', 'tract', 'The real estate company bought a large tract of land for development.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('czuwanie', 'vigil', 'The family kept a vigil at the bedside of the sick loved one.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zmęczony', 'weary', 'She was feeling weary after a long day of work.', 'ADJECTIVE', 'HARD');
--15
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przylgnąć', 'adhere', 'The wall adheres to the concrete surface.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zarządzać', 'administer', 'The nurse will administer the injection.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pełen współczucia', 'compassionate', 'The doctor was very compassionate and understanding.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zanieczyszczony', 'contaminate', 'The factory was accused of contaminating the river.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('deficyt', 'deficiency', 'A lack of vitamin C can lead to a deficiency.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('epidemia', 'epidemic', 'The flu has become an epidemic.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('bezpieczeństwo', 'safety', 'The workers emphasized the importance of safety.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('konieczny', 'imperative', 'It is imperative to arrive on time for the meeting.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('jelita', 'intestines', 'The food moves through the intestines and is absorbed into the bloodstream.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('objawiać się', 'manifest', 'The symptoms of the disease began to manifest.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('metaboliczny', 'metabolic', 'A metabolic disorder can affect the body*s ability to process food.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przepełniony', 'overcrowded', 'The city*s streets were overcrowded with people.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nadrzędny', 'paramount', 'The safety of the passengers is of paramount importance.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('praktykant', 'practitioner', 'The practitioner prescribed medication to treat the patients condition.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zaopatrzenie', 'provision', 'The company made provisions for emergencies.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odnowić', 'replenish', 'You need to replenish your supply of water every day.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('sterylny', 'sterile', 'The surgical instruments were cleaned and stored in a sterile environment.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('modernizować', 'upgrade', 'The company plans to upgrade its computer system.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odpowiedni', 'viable', 'The company needs to find a viable solution to the problem.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('dobrowolny', 'voluntary', 'The program is voluntary and participants can choose to opt out.', 'ADJECTIVE', 'HARD');
--16
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pośrodku', 'amid', 'Amid the chaos, they managed to stay calm.', 'PREPOSITION', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('za kulisami', 'backstage', 'She got a chance to go backstage and meet the performers.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('milioner', 'billionaire', 'The billionaire invested in a new company.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('brutalny', 'brute', 'The brute force of the wind knocked down the trees.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('niezręczny', 'clumsy', 'She was so clumsy that she kept dropping things.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zderzać się', 'collide', 'The two cars collided and were badly damaged.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('winny', 'culprit', 'The police were looking for the culprit who stole the money.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ewakuować', 'evacuate', 'The residents were ordered to evacuate the area due to the approaching storm.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('łatwopalny', 'flammable', 'The label on the bottle warned that the contents were flammable.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('tłum', 'mob', 'A mob of angry protesters gathered outside the building.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przedwczesny', 'premature', 'The doctor said that the baby was born premature and would need special care.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('urazać', 'resent', 'She resented the fact that he never appreciated her hard work.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('satyra', 'satire', 'The movie was a satire on modern society.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('dokładne rozpatrywanie', 'scrutiny', 'The company*s finances were under scrutiny by the authorities.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('segregować', 'segregate', 'The school had to integrate its classrooms after being accused of segregating its students.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('podmiot', 'subject', 'The subject of the lecture was the history of the city.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zaświadczać', 'testify', 'He was called to testify in court about what he saw on the night of the crime.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('burza', 'tumult', 'The market was in a state of tumult as the news broke.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nieodpowiednio ocenić', 'underestimate', 'They underestimated the strength of the opposition and lost the game.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('hałas', 'uproar', 'The uproar from the fans was so loud that the players could hardly hear each other.', 'NOUN', 'HARD');
--17
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przyspieszyć', 'accelerate', 'The car accelerated quickly down the highway.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('na nowo', 'anew', 'We need to start the project anew.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wada', 'defect', 'The product was returned due to a defect.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('smutny', 'dreary', 'The dreary weather matched her mood.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('podwójny', 'duplicate', 'He made a duplicate copy of the key.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('elektromagnetyczny', 'electromagnetic', 'Electromagnetic radiation is produced by the movement of electric charges.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('elektron', 'electron', 'Electrons are negatively charged particles that orbit the nucleus of an atom.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('płynąć', 'glide', 'The bird glided through the air with ease.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pomysłowy', 'ingenious', 'The young inventor came up with an ingenious solution to the problem.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('innowacja', 'innovation', 'Innovation is the key to success in today*s competitive market.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('innowacyjny', 'innovative', 'The company is known for its innovative products.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('uruchomić', 'launch', 'NASA is preparing to launch a new satellite.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('meteorologiczny', 'meteorological', 'Meteorological conditions can have a major impact on weather patterns.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('meteorologia', 'meteorology', 'Meteorology is the scientific study of the Earth*s atmosphere and its processes.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('penetrować', 'penetrate', 'The bullet penetrated the wall.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ciągnięcie', 'propulsion', 'The propulsion system provides the energy needed to move the spacecraft.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('symulować', 'simulate', 'We use computer simulations to model complex systems.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('podburzać', 'spur', 'The promise of a reward spurred the workers to greater efforts.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('stymulować', 'stimulate', 'The new program is designed to stimulate economic growth.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wytrwały', 'tenacious', 'She was a tenacious advocate for the rights of workers.', 'ADJECTIVE', 'HARD');
--18
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wcześniej', 'beforehand', 'She prepared everything beforehand so she would not forget anything on the day of the event.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('stopnie Celsjusza', 'centigrade', 'The temperature outside was 30 degrees centigrade.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('gwar', 'chatter', 'The chatter in the room was so loud that it was difficult to hear what was being said.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('koncert', 'concerto', 'She played a beautiful piano concerto in front of the whole audience.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('skondensować', 'condense', 'The gas in the container slowly started to condense and become a liquid.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zatoka', 'cove', 'They spent the day lounging on the sandy beach of a secluded cove.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pogorszyć się', 'deteriorate', 'The condition of the old building had deteriorated over the years due to lack of maintenance.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zewnętrzny', 'exterior', 'He was so impressed with the beautiful exterior of the building that he decided to take a tour inside.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('autostrada', 'freeway', 'The traffic was heavy on the freeway so it took them longer to reach their destination.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('serdeczny', 'hearty', 'They shared a hearty meal together and laughed until their bellies ached.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('gościnny', 'hospitable', 'The family was very hospitable and made sure their guests felt comfortable during their stay.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('dwór', 'manor', 'The wealthy lord lived in a grand manor with servants at his beck and call.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('klasztor', 'monastery', 'The quiet and peaceful atmosphere of the monastery was perfect for the young man who sought solitude and reflection.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('szklarnia', 'nursery', 'The young couple visited the nursery to select plants for their garden.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wysunięty', 'outstretched', 'She outstretched her arms in an attempt to reach the high shelf.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('paczka', 'parcel', 'The delivery man brought a parcel for her, but she was not at home to receive it.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('profil', 'profile', 'She created a profile on the dating website and started browsing through potential matches.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('żywiołowy', 'vivacious', 'Her vivacious personality made her the life of the party and everyone loved her.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wijący się', 'winding', 'They followed the winding road through the mountains until they reached the scenic lookout.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zamek błyskawiczny', 'zip', 'He quickly zip up his jacket to keep out the cold wind.', 'VERB', 'HARD');
--19
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('droga powietrzna', 'airway', 'The airway is the path that air follows to get into and out of the lungs.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('Wszechmogący', 'Almighty', 'The Almighty is often used to refer to God or a deity in monotheistic religions.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nadejście', 'advent', 'Advent is the arrival or arrival of something or someone important.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('gromada gwiazd', 'constellation', 'A constellation is a group of stars that are recognized as a recognizable pattern.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('ostateczny', 'definitive', 'The definitive answer is the final, authoritative, and unambiguous answer to a question.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('równoważyć', 'equate', 'To equate two things means to consider them equal or to consider them as having the same value or importance.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wdychać', 'inhale', 'To inhale is to breathe in air or other gases.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wołać', 'invoke', 'To invoke means to call upon or bring into action.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('księżycowy', 'lunar', 'Lunar refers to anything related to the moon or its phases.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('nowość', 'novelty', 'Novelty is the quality of being new, unusual, or different.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przestarzały', 'outmoded', 'Outmoded means outdated, no longer fashionable or current, or no longer in use.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('spersonalizować', 'personalize', 'To personalize means to make something individual or customized to a particular person.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('dotyczyć', 'pertain', 'To pertain means to relate or be relevant to a particular subject or matter.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pierwotny', 'primal', 'Primal means fundamental, original, or having to do with the earliest stages of development.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('psychiatryczny', 'psychiatric', 'Psychiatric refers to anything related to psychiatry, the medical specialty dealing with mental illness and abnormal behavior.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('psychiatria', 'psychiatry', 'Psychiatry is the medical specialty dealing with mental illness and abnormal behavior.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odruch', 'reflex', 'A reflex is an automatic, rapid, and unconscious response to a stimulus.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('napad', 'seizure', 'A seizure is an episode of abnormal electrical activity in the brain that can cause a variety of symptoms, such as convulsions, muscle contractions, and changes in consciousness.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('sesja', 'session', 'A session is a meeting or series of meetings for a specific purpose, such as a legislative session, a therapy session, or a musical recording session.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('narzędzie', 'utensil', 'She reached for the utensil drawer to grab a spoon.', 'NOUN', 'HARD');
--20
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('klejący', 'adhesive', 'She used an adhesive to stick the picture to the wall.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odwrotny', 'adverse', 'The adverse weather conditions made the journey difficult.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('zależność', 'dependency', 'There is a dependency between the number of hours of sleep and academic performance.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wysypisko śmieci', 'dump', 'The garbage was taken to the dump.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wieczny', 'eternal', 'People believe that the soul is eternal.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('wahający się', 'fluctuate', 'The price of oil fluctuated greatly over the last year.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('od', 'fro', 'He rubbed his hands together to warm them, blowing on his fingers to ward off the fro.', 'ADVERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('układanka', 'inclusion', 'The inclusion of more vegetables in his diet improved his health.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pośredni', 'intermediate', 'She took an intermediate Spanish course to improve her language skills.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('przerywany', 'intermittent', 'The rain was intermittent, coming and going throughout the day.', 'ADJECTIVE', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('mentor', 'mentor', 'She found a mentor who helped guide her through the early stages of her career.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('feniks', 'phoenix', 'The phoenix is a mythical bird that is said to be reborn from its ashes.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('fotosynteza', 'photosynthesis', 'Plants undergo photosynthesis to convert light energy into chemical energy.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('pyłek', 'pollen', 'The bees collect pollen from flowers to make honey.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odzyskać', 'regain', 'After the surgery, he regained the ability to walk.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('odwrócić', 'reverse', 'He reversed the car into the parking spot.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('rój', 'swarm', 'A swarm of bees surrounded the hive.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('faktura', 'texture', 'The rough texture of the bark made it easy for the climbers to climb the tree.', 'NOUN', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('drażnić', 'tickle', 'The feather tickled her nose, making her sneeze.', 'VERB', 'HARD');
INSERT INTO word (pl, eng, eng_usage, type, difficulty) VALUES ('tętniący życiem', 'vibrant', 'The city was vibrant with people, music, and lights.', 'ADJECTIVE', 'HARD');